%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.6

-ifndef(pb_client).
-define(pb_client, true).

-define(pb_client_gpb_version, "4.19.6").

-ifndef('REQ_HEARTBEAT_PB_H').
-define('REQ_HEARTBEAT_PB_H', true).
-record(req_heartbeat,
        {client_time = 0        :: non_neg_integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-ifndef('RESP_HEARTBEAT_PB_H').
-define('RESP_HEARTBEAT_PB_H', true).
-record(resp_heartbeat,
        {client_time = 0        :: non_neg_integer() | undefined, % = 1, optional, 32 bits
         server_time = 0        :: non_neg_integer() | undefined % = 2, optional, 32 bits
        }).
-endif.

-endif.
