%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.6

-ifndef(pb_shop).
-define(pb_shop, true).

-define(pb_shop_gpb_version, "4.19.6").

-ifndef('SHOP_INFO_PB_H').
-define('SHOP_INFO_PB_H', true).
-record(shop_info,
        {id = 0                 :: non_neg_integer() | undefined, % = 1, optional, 32 bits
         name = <<>>            :: unicode:chardata() | undefined, % = 2, optional
         address = <<>>         :: unicode:chardata() | undefined % = 3, optional
        }).
-endif.

-ifndef('REQ_SHOP_INFO_PB_H').
-define('REQ_SHOP_INFO_PB_H', true).
-record(req_shop_info,
        {
        }).
-endif.

-ifndef('RESP_SHOP_INFO_PB_H').
-define('RESP_SHOP_INFO_PB_H', true).
-record(resp_shop_info,
        {shop_list = []         :: [pb_shop:shop_info()] | undefined % = 1, repeated
        }).
-endif.

-endif.
